-- ============================================================
-- ENUMS
-- ============================================================

CREATE TYPE neuron_status AS ENUM ('active', 'frozen');
CREATE TYPE neurotransmitter_type AS ENUM ('excitatory', 'inhibitory', 'unknown');
CREATE TYPE connection_status AS ENUM ('positive', 'negative', 'unknown');
CREATE TYPE fragment_type AS ENUM ('data', 'protocol', 'animal');
CREATE TYPE error_type AS ENUM ('std', 'sem');
CREATE TYPE evidence_relation_type AS ENUM ('interpretation', 'inference');

-- ============================================================
-- SUBREGION lookup
-- ============================================================

CREATE TABLE subregion (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  display_order INT NOT NULL
);

INSERT INTO subregion (id, name, display_order) VALUES
  ('DG', 'Dentate Gyrus', 1),
  ('CA3', 'CA3', 2),
  ('CA2', 'CA2', 3),
  ('CA1', 'CA1', 4),
  ('Sub', 'Subiculum', 5),
  ('EC', 'Entorhinal Cortex', 6);

-- ============================================================
-- NEURON TYPE (central entity)
-- ============================================================

CREATE TABLE neuron_type (
  id INT PRIMARY KEY,
  subregion_id TEXT NOT NULL REFERENCES subregion(id),
  name TEXT NOT NULL,
  nickname TEXT NOT NULL,
  status neuron_status NOT NULL DEFAULT 'active',
  excit_inhib neurotransmitter_type NOT NULL DEFAULT 'unknown',
  supertype TEXT,
  type_subtype TEXT,
  position INT,
  ranks TEXT,
  notes TEXT,
  explanatory_notes TEXT,
  v2p0 BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  search_vector TSVECTOR GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(nickname, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(name, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(notes, '')), 'D')
  ) STORED
);

CREATE INDEX idx_neuron_type_search ON neuron_type USING GIN (search_vector);
CREATE INDEX idx_neuron_type_subregion ON neuron_type(subregion_id);
CREATE INDEX idx_neuron_type_status ON neuron_type(status);

-- ============================================================
-- ARTICLES
-- ============================================================

CREATE TABLE article (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  pmid_isbn BIGINT,
  pmcid TEXT,
  nihmsid TEXT,
  doi TEXT,
  open_access BOOLEAN,
  title TEXT,
  publication TEXT,
  volume TEXT,
  issue TEXT,
  first_page INT,
  last_page INT,
  year TEXT,
  citation_count INT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  search_vector TSVECTOR GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(publication, '')), 'B')
  ) STORED
);

CREATE INDEX idx_article_search ON article USING GIN (search_vector);
CREATE INDEX idx_article_pmid ON article(pmid_isbn);

-- ============================================================
-- AUTHORS
-- ============================================================

CREATE TABLE author (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);

CREATE TABLE article_author (
  article_id INT NOT NULL REFERENCES article(id),
  author_id INT NOT NULL REFERENCES author(id),
  position INT,
  PRIMARY KEY (article_id, author_id)
);

-- ============================================================
-- EVIDENCE
-- ============================================================

CREATE TABLE evidence (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE article_evidence (
  article_id INT NOT NULL REFERENCES article(id),
  evidence_id INT NOT NULL REFERENCES evidence(id),
  PRIMARY KEY (article_id, evidence_id)
);

CREATE TABLE evidence_evidence (
  parent_evidence_id INT NOT NULL REFERENCES evidence(id),
  child_evidence_id INT NOT NULL REFERENCES evidence(id),
  relation_type evidence_relation_type NOT NULL,
  PRIMARY KEY (parent_evidence_id, child_evidence_id)
);

-- ============================================================
-- PROPERTY (subject/predicate/object triples)
-- ============================================================

CREATE TABLE property (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  subject TEXT NOT NULL,
  predicate TEXT NOT NULL,
  object TEXT NOT NULL
);

CREATE INDEX idx_property_subject ON property(subject);
CREATE INDEX idx_property_triple ON property(subject, predicate, object);

-- Key junction table: links evidence + property + neuron type + article
CREATE TABLE evidence_property_type (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  evidence_id INT NOT NULL REFERENCES evidence(id),
  property_id INT NOT NULL REFERENCES property(id),
  type_id INT NOT NULL REFERENCES neuron_type(id),
  article_id INT REFERENCES article(id),
  priority INT,
  unvetted BOOLEAN NOT NULL DEFAULT false,
  linking_quote TEXT,
  interpretation_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ept_type ON evidence_property_type(type_id);
CREATE INDEX idx_ept_property ON evidence_property_type(property_id);
CREATE INDEX idx_ept_evidence ON evidence_property_type(evidence_id);

-- ============================================================
-- FRAGMENT (text quotes from papers)
-- ============================================================

CREATE TABLE fragment (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  original_id INT,
  quote TEXT,
  page_location TEXT,
  fragment_type fragment_type,
  attachment TEXT,
  attachment_type TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  search_vector TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('english', coalesce(quote, ''))
  ) STORED
);

CREATE INDEX idx_fragment_search ON fragment USING GIN (search_vector);

CREATE TABLE evidence_fragment (
  evidence_id INT NOT NULL REFERENCES evidence(id),
  fragment_id INT NOT NULL REFERENCES fragment(id),
  PRIMARY KEY (evidence_id, fragment_id)
);

CREATE TABLE fragment_type_rel (
  fragment_id INT NOT NULL REFERENCES fragment(id),
  type_id INT NOT NULL REFERENCES neuron_type(id),
  priority INT,
  PRIMARY KEY (fragment_id, type_id)
);

-- ============================================================
-- SYNONYM
-- ============================================================

CREATE TABLE synonym (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,

  search_vector TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('english', name)
  ) STORED
);

CREATE INDEX idx_synonym_search ON synonym USING GIN (search_vector);

CREATE TABLE synonym_type (
  synonym_id INT NOT NULL REFERENCES synonym(id),
  type_id INT NOT NULL REFERENCES neuron_type(id),
  PRIMARY KEY (synonym_id, type_id)
);

CREATE TABLE article_synonym (
  article_id INT NOT NULL REFERENCES article(id),
  synonym_id INT NOT NULL REFERENCES synonym(id),
  PRIMARY KEY (article_id, synonym_id)
);

-- ============================================================
-- MARKER DATA
-- ============================================================

CREATE TABLE marker_data (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  expression TEXT,
  animal TEXT,
  protocol TEXT
);

CREATE TABLE evidence_marker_data (
  evidence_id INT NOT NULL REFERENCES evidence(id),
  marker_data_id INT NOT NULL REFERENCES marker_data(id),
  PRIMARY KEY (evidence_id, marker_data_id)
);

-- ============================================================
-- ELECTROPHYSIOLOGY DATA
-- ============================================================

CREATE TABLE ep_data (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  raw TEXT,
  value1 TEXT,
  value2 TEXT,
  error TEXT,
  std_sem error_type,
  n TEXT,
  istim TEXT,
  time_val TEXT,
  unit TEXT,
  location TEXT
);

CREATE TABLE ep_data_evidence (
  ep_data_id INT NOT NULL REFERENCES ep_data(id),
  evidence_id INT NOT NULL REFERENCES evidence(id),
  PRIMARY KEY (ep_data_id, evidence_id)
);

-- ============================================================
-- CONNECTIVITY
-- ============================================================

CREATE TABLE type_connection (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_type_id INT NOT NULL REFERENCES neuron_type(id),
  target_type_id INT NOT NULL REFERENCES neuron_type(id),
  connection_status connection_status NOT NULL DEFAULT 'unknown',
  connection_location TEXT
);

CREATE INDEX idx_conn_source ON type_connection(source_type_id);
CREATE INDEX idx_conn_target ON type_connection(target_type_id);

-- Dense connectivity from conndata.csv
CREATE TABLE connectivity_data (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_type_id INT NOT NULL REFERENCES neuron_type(id),
  target_type_id INT NOT NULL REFERENCES neuron_type(id),
  layers TEXT NOT NULL
);

CREATE INDEX idx_conndata_source ON connectivity_data(source_type_id);
CREATE INDEX idx_conndata_target ON connectivity_data(target_type_id);

-- ============================================================
-- SYNAPSE PROBABILITY
-- ============================================================

CREATE TABLE synapse_probability (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_type_id INT NOT NULL REFERENCES neuron_type(id),
  target_type_id INT NOT NULL REFERENCES neuron_type(id),
  sp_mean DOUBLE PRECISION,
  sp_stdev DOUBLE PRECISION
);

CREATE TABLE number_of_contacts (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_type_id INT NOT NULL REFERENCES neuron_type(id),
  target_type_id INT NOT NULL REFERENCES neuron_type(id),
  noc_mean DOUBLE PRECISION,
  noc_stdev DOUBLE PRECISION
);

CREATE TABLE number_of_potential_synapses (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_type_id INT NOT NULL REFERENCES neuron_type(id),
  target_type_id INT NOT NULL REFERENCES neuron_type(id),
  nops_mean DOUBLE PRECISION,
  nops_stdev DOUBLE PRECISION
);

-- ============================================================
-- NEURITE MORPHOMETRICS
-- ============================================================

CREATE TABLE neurite_length (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type_id INT NOT NULL REFERENCES neuron_type(id),
  parcel TEXT NOT NULL,
  neurite_id INT,
  total_length_avg DOUBLE PRECISION,
  total_length_std DOUBLE PRECISION,
  values_count INT
);

CREATE INDEX idx_neurite_type ON neurite_length(type_id);

CREATE TABLE somatic_distance (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type_id INT NOT NULL REFERENCES neuron_type(id),
  parcel TEXT NOT NULL,
  neurite_id INT,
  sd_avg DOUBLE PRECISION,
  sd_std DOUBLE PRECISION,
  values_count INT,
  sd_min DOUBLE PRECISION,
  sd_max DOUBLE PRECISION
);

-- ============================================================
-- POPULATION COUNTS
-- ============================================================

CREATE TABLE population_count (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type_id INT NOT NULL REFERENCES neuron_type(id),
  count_value INT,
  lower_bound INT,
  upper_bound INT
);

-- ============================================================
-- FIRING PATTERN
-- ============================================================

CREATE TABLE firing_pattern (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type_id INT NOT NULL REFERENCES neuron_type(id),
  overall_fp TEXT,
  delay_ms NUMERIC,
  pfs_ms NUMERIC,
  swa_mv NUMERIC,
  n_isi INT,
  isi_avg_ms NUMERIC,
  sd_ms NUMERIC,
  max_isi_ms NUMERIC,
  min_isi_ms NUMERIC,
  first_isi_ms NUMERIC,
  last_isi_ms NUMERIC,
  accommodation_index NUMERIC,
  -- All parameters in JSONB for the long tail
  parameters JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX idx_fp_type ON firing_pattern(type_id);

-- ============================================================
-- IZHIKEVICH SIMULATION MODELS
-- ============================================================

CREATE TABLE izh_model (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type_id INT NOT NULL REFERENCES neuron_type(id),
  name TEXT,
  preferred BOOLEAN NOT NULL DEFAULT false,
  is_multi_compartment BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_izh_type ON izh_model(type_id);

CREATE TABLE izh_compartment (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  model_id INT NOT NULL REFERENCES izh_model(id) ON DELETE CASCADE,
  compartment_index INT NOT NULL,
  k DOUBLE PRECISION,
  a DOUBLE PRECISION,
  b DOUBLE PRECISION,
  d DOUBLE PRECISION,
  capacitance DOUBLE PRECISION,
  v_rest DOUBLE PRECISION,
  v_threshold DOUBLE PRECISION,
  v_peak DOUBLE PRECISION,
  v_min DOUBLE PRECISION,
  coupling_g DOUBLE PRECISION,
  coupling_p DOUBLE PRECISION,
  UNIQUE(model_id, compartment_index)
);

-- ============================================================
-- TSODYKS-MARKRAM SYNAPSE MODEL
-- ============================================================

CREATE TABLE tm_synapse_model (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_type_id INT NOT NULL REFERENCES neuron_type(id),
  target_type_id INT NOT NULL REFERENCES neuron_type(id),
  conductance_mean DOUBLE PRECISION,
  conductance_min DOUBLE PRECISION,
  conductance_max DOUBLE PRECISION,
  tau_d_mean DOUBLE PRECISION,
  tau_d_min DOUBLE PRECISION,
  tau_d_max DOUBLE PRECISION,
  tau_r_mean DOUBLE PRECISION,
  tau_r_min DOUBLE PRECISION,
  tau_r_max DOUBLE PRECISION,
  tau_f_mean DOUBLE PRECISION,
  tau_f_min DOUBLE PRECISION,
  tau_f_max DOUBLE PRECISION,
  utilization_mean DOUBLE PRECISION,
  utilization_min DOUBLE PRECISION,
  utilization_max DOUBLE PRECISION,
  species TEXT,
  sex TEXT,
  age TEXT,
  temperature TEXT,
  recording_mode TEXT
);

-- ============================================================
-- OSCILLATION PHASES
-- ============================================================

CREATE TABLE oscillation_phase (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type_id INT NOT NULL REFERENCES neuron_type(id),
  theta TEXT,
  swr_ratio TEXT,
  other TEXT
);

-- ============================================================
-- GENE EXPRESSION
-- ============================================================

CREATE TABLE gene_expression (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type_id INT NOT NULL REFERENCES neuron_type(id),
  gene_name TEXT NOT NULL,
  parcel TEXT NOT NULL,
  expression_level DOUBLE PRECISION,
  confidence DOUBLE PRECISION
);

CREATE INDEX idx_gene_type ON gene_expression(type_id);
CREATE INDEX idx_gene_name ON gene_expression(gene_name);

-- ============================================================
-- HIPPOCAMPOME TO NMO MAPPING
-- ============================================================

CREATE TABLE hippocampome_nmo (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type_id INT NOT NULL REFERENCES neuron_type(id),
  nmo_id TEXT
);

-- ============================================================
-- PARCEL LOOKUP (for synapse probability)
-- ============================================================

CREATE TABLE parcel (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);
